"""Render a human-readable facts view from a Documents domain's YAML facts."""

from __future__ import annotations

import argparse
import datetime as dt
from collections import Counter
from pathlib import Path

import yaml

TYPE_DISPLAY = {
    "budget": ("💰预算", "预算/资金"),
    "progress": ("📊进度", "进度/指标"),
    "config": ("📁配置", "配置/规模"),
    "event": ("📅事件", "事件/时点"),
    "structure": ("🏛️结构", "结构/机制"),
    "rule": ("📜规则", "规则/政策"),
    "info": ("📄信息", "信息/事实"),
    "relation": ("👤关系", "关系/人事"),
    "indicator": ("📐指标", "指标/量化"),
}
ORDER = tuple(TYPE_DISPLAY)
IMPORTANCE = {"high": "🔴", "medium": "🟡", "low": "🔵"}


def _facts(domain_root: Path) -> dict[str, list[dict[str, object]]]:
    grouped = {kind: [] for kind in ORDER}
    for path in sorted((domain_root / "_entities" / "facts").glob("[0-9][0-9]-*.yaml")):
        document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for fact in document.get("facts", []):
            if isinstance(fact, dict):
                grouped.setdefault(str(fact.get("type", "info")), []).append(fact)
    return grouped


def _cell(value: object) -> str:
    if value is None or value == "":
        return "-"
    if isinstance(value, list):
        return ", ".join(str(item) for item in value) or "-"
    return str(value)


def render(domain_root: Path) -> str:
    grouped = _facts(domain_root)
    total = sum(len(items) for items in grouped.values())
    today = dt.datetime.now(dt.UTC).date().isoformat()
    by_type = Counter({kind: len(items) for kind, items in grouped.items()})
    lines = [
        "<!-- Generated by Workspace Runtime; YAML is the canonical facts source. -->",
        "---",
        "title: 事实基座（YAML 双轨·生成视图）",
        "description: 人类视图。机器可读真源在 _entities/facts/*.yaml；本文件由 Workspace Runtime 生成，勿手改。",
        "status: active",
        "type: canonical",
        f"generated: {today}",
        "tags: [事实面, 事实层, yaml-ssot]",
        "---",
        "",
        "# 事实基座 — Facts（生成视图）",
        "",
        f"> **YAML 双轨 SSOT**：机器可读真源为 [`facts/`](facts/)（{total} 条），本文件为生成视图。",
        "> 日常校验：`runtime documents run documents-weijian-facts-audit --json`。",
        "",
        "## 统计",
        "",
        "| 类型 | 条数 | 说明 |",
        "|------|:----:|------|",
    ]
    for kind in ORDER:
        emoji, label = TYPE_DISPLAY[kind]
        lines.append(f"| {emoji} {label} | {by_type[kind]} | `{kind}` |")
    lines.extend([f"| **合计** | **{total}** | YAML 真源 |", ""])
    for kind in ORDER:
        emoji, label = TYPE_DISPLAY[kind]
        facts = grouped[kind]
        lines.extend(
            [
                f"## {emoji} {label}（{len(facts)}）",
                "",
                "| fid | 摘要 | 数值 | 重要性 | 来源 | 可信度 | 验证日 | 过期日 | 关联实体 |",
                "|-----|------|:----:|:------:|------|:------:|:------:|:------:|---------|",
            ]
        )
        for fact in facts:
            lines.append(
                "| `{fid}` | {summary} | {value} | {importance} | {source} | {trust} | {verified_at} | {expiry} | {entities} |".format(
                    fid=_cell(fact.get("fid")),
                    summary=_cell(fact.get("summary")),
                    value=_cell(fact.get("value")),
                    importance=IMPORTANCE.get(str(fact.get("importance")), "🔵"),
                    source=_cell(fact.get("source")),
                    trust=_cell(fact.get("trust")),
                    verified_at=_cell(fact.get("verified_at")),
                    expiry=_cell(fact.get("expiry")),
                    entities=_cell(fact.get("entity_ids")),
                )
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path, help="Documents 域根目录")
    parser.add_argument(
        "--out", type=Path, help="生成视图路径（默认 _entities/facts.md）"
    )
    args = parser.parse_args()
    domain = args.root.expanduser().resolve()
    output = (
        args.out.expanduser().resolve()
        if args.out
        else domain / "_entities" / "facts.md"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(domain) + "\n", encoding="utf-8")
    print(f"generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
