from .shared import RUNTIME_HOME, _run_script


def _matrix_list() -> str:
    from runtime.matrix import list_services

    services = list_services()
    parts = [f"{'NAME':20s} {'TYPE':12s} {'PORT':6s} {'STATUS':12s}", "-" * 60]
    for s in services:
        port = str(s.port) if s.port else "—"
        parts.append(f"{s.name:20s} {s.type:12s} {port:6s} {s.status:12s}")
    return "\n".join(parts)


def _matrix_get(name: str) -> str:
    from runtime.matrix import get_service, resolve_path

    svc = get_service(name)
    if not svc:
        return f"❌ Service not found: {name}"
    lines = [
        f"Name:     {svc.name}",
        f"Type:     {svc.type}",
        f"Status:   {svc.status}",
    ]
    if svc.port:
        lines.append(f"Port:     {svc.port}")
    if svc.launchd_label:
        lines.append(f"Launchd:  {svc.launchd_label}")
    if svc.health_url:
        lines.append(f"Health:   {svc.health_url}")
    if svc.docker_container:
        lines.append(f"Docker:   {svc.docker_container}")
    dp = resolve_path(svc.deploy_path)
    if dp:
        lines.append(f"Deploy:   {dp}")
    lp = resolve_path(svc.log_path)
    if lp:
        lines.append(f"Logs:     {lp}")
    return "\n".join(lines)


TOOLS = [
    {
        "name": "runtime_health",
        "description": "Run a full health scan of all services. Returns JSON state generated by ecos-matrix-scheduler.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: (
            (RUNTIME_HOME / "matrix_state.json").read_text()
            if (RUNTIME_HOME / "matrix_state.json").exists()
            else "State not found. Is Matrix Scheduler running?"
        ),
    },
    {
        "name": "runtime_matrix_list",
        "description": "List all services in the runtime matrix.",
        "inputSchema": {"type": "object", "properties": {}},
        "handler": lambda args: _matrix_list(),
    },
    {
        "name": "runtime_matrix_get",
        "description": "Get detailed info about a specific service.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string", "description": "Service name"}},
            "required": ["name"],
        },
        "handler": lambda args: _matrix_get(args["name"]),
    },
    {
        "name": "runtime_service_ctl",
        "description": "Start, stop, restart, or check status of a service.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Service name"},
                "action": {
                    "type": "string",
                    "enum": ["status", "start", "stop", "restart"],
                },
            },
            "required": ["name", "action"],
        },
        "handler": lambda args: _run_script(
            "service-ctl.sh", args["name"], args["action"]
        ),
    },
]
